### ISSUE TITLE
Reupload of CSV rate error

### ISSUE THREAD

**Issue by firdaussoberi** [massimo-zaniboni/asterisell-v5#9]
Hi,

First of all I want to thank you for this wonderful application.

I managed to install and import CDRS as well as doing rating as per CSV list, and also play around with new instances and rerating. 
However when I try to change the CSV list via upload it shows the following error:

<img width="1279" alt="Screenshot 2021-11-05 at 4 57 00 AM" src="https://user-images.githubusercontent.com/8426299/140419451-cb3c75ce-c39f-4682-8477-40634b0c5582.png">
<img width="1280" alt="Screenshot 2021-11-05 at 4 57 08 AM" src="https://user-images.githubusercontent.com/8426299/140419459-522714c8-0ff9-4db9-a3e1-572402e87dec.png">

I tried to dig further and see these CSV files are saved as blob in ar_rate table, however I could not find the specific code that runs the rate/save part (I did found apps/asterisell/modules/rate/actions/actions.class.php) but this does not seem to have the specific file upload part. I could do manual replacement to the blob file in the table, but this does not seems to solve the problem.

This only happens with csv file but note the rate plan language file itself (if I change say main-rate-cost this is fine, but not say csv-1).
I know you may not want to support anymore as this is quite an extensive application, but
could you kindly guide me on how to fix this issue? I would really appreciate it.

Regards,
Firdaus

**Comment by massimo-zaniboni** [comment]
Hi, I have a new version with a lot of changes/improvements that it is used in production from few customers.

In the weekend I will updatethe OSS repository with it. I modified also parts of the code you are citing, so it is better for me to postpone the discusion using the new version.

It is strange that you were able to install using this version, because I improved/fixed the installer.

**Comment by firdaussoberi** [comment]
Hi,

Thanks!
Would be interested in that too.

Yeah, took a lot of tinkering and digging the codes to come to this point. But one of the best CDRS tools I ever found!

**Comment by massimo-zaniboni** [comment]
I updated with the 6.4 version. You can try again with the last version.

**Comment by massimo-zaniboni** [comment]
> I tried to dig further and see these CSV files are saved as blob in ar_rate table, however I could not find the specific code that runs the rate/save part (I did found apps/asterisell/modules/rate/actions/actions.class.php) but this does not seem to have the specific file upload part. I could do manual replacement to the blob file in the table, but this does not seems to solve the problem.

I'm using Symfony 1.3 framework. It is rather old. By the way I should port at least to https://github.com/FriendsOfSymfony1/symfony1.

If you see the code

```
class rateActions extends autoRateActions
```
``autoRateActions`` is a class generated automatically from Symfony framework. You can check the code, connecting to a running instance, opening at least one time the ``rate`` form (so Symfony generate the code) and then check the code.

```
fab connect:asterisell/demo
# MANUAL TASK: access the form on the web browser 
less cache/asterisell/prod/modules/autoRate/actions/autoRateActions.php
```

Also, the logic for saving the rate can be found in ``lib/model/ArRate.php`` and parent classes.

**Comment by firdaussoberi** [comment]
Sorry for the long delay, I just had the chance to get back to it.

I already tried v6.4 and this seems to fix it. 
Will try to see what's more in this current version.
Thanks for your help! Closing this...

**Comment by massimo-zaniboni** [comment]
New releases of nginx from epel repository are using the ``nginx`` user instead of the ``apache`` user, used from CentOS 7 by default. Sometime a directory ``/var/lib/nginx/tmp`` is created, with the user ``nginx``, and big CSV files are saved there, during upload. This generate a permission error.

I will improve the installation process in these days.

**Comment by firdaussoberi** [comment]
Hi, probably this is not related, but I am a bit confused by the format of cdrs importing from DB (external collector).

Currently I managed to import through csv files by following apps/asterisell/lib/jobs/data_file_processing and by copying format in folder say:
/var/www/test_instance/admin/data_files/messages/input/

However I also saw in the manual that connection to external database cdr is also possible.
https://www.asterisell.com/manual/importing-of-cdrs.html#Importing_of_CDRS

It mentioned:
"
The prefix import-remote-cdrs- will be used from the job ImportCDRSUsingAppConfs for retrieving the data from the remote MySQL database, assuming it is in the abilis-db-collector format.
"
I am using 'asterisell-standard', 'v1' with standard format following ar_source_cdr example (with added SIP channel constants):
2021-12-09 13:37:12,\N,outgoing,false,ANSWERED,283,10011,6012345678,,SIP-general-operator,

I saw in ar_source_cdr table that the format is stored in 'content' column. Does the format of the external database table where cdr record is stored has to match same columns as in ar_source_cdr (namely having columns calldate, id, ar_cdr_provider_id, ar_physical_format_id, content, is_hacked)? or the column names need to be in same name as in specified by 
rating_tools/rate_engine/src/Asterisell/Cdr.hs 

I already tried setting it up in asterisell_instances.py however it does not seem to import cdr this way.
If possible, could you guide me to set the conf_connection_params and also the format matching? I would really appreciate it. So far, the billing and rating is working well and I can generate the invoice (even change its format in InvoiceCalcStore.php) . 

Thank you so much :D

**Comment by massimo-zaniboni** [comment]
@firdaussoberi can you move this on the new created "discussion" section? So the help will remain.

**Comment by firdaussoberi** [comment]
> @firdaussoberi can you move this on the new created "discussion" section? So the help will remain.

Hi, yes sure
